/* GENERATED by generate.py — the campaign polygon. */
import type { FeatureCollection } from '@/core/types';

export const BOUNDARY = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"name":"Southwest Memphis Community Air Monitoring"},"geometry":{"type":"Polygon","coordinates":[[[-90.1735,35.0345],[-90.153,35.0205],[-90.118,35.016],[-90.0855,35.0245],[-90.0678,35.0465],[-90.0662,35.0795],[-90.0795,35.1025],[-90.1025,35.1155],[-90.1335,35.1125],[-90.1565,35.0935],[-90.1735,35.0345]]]}}]} as unknown as FeatureCollection;
